# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Symbols(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, symbols=None):  # noqa: E501
        """Symbols - a model defined in OpenAPI

        :param symbols: The symbols of this Symbols.  # noqa: E501
        :type symbols: str
        """
        self.openapi_types = {
            'symbols': str
        }

        self.attribute_map = {
            'symbols': 'symbols'
        }

        self._symbols = symbols

    @classmethod
    def from_dict(cls, dikt) -> 'Symbols':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Symbols of this Symbols.  # noqa: E501
        :rtype: Symbols
        """
        return util.deserialize_model(dikt, cls)

    @property
    def symbols(self):
        """Gets the symbols of this Symbols.


        :return: The symbols of this Symbols.
        :rtype: str
        """
        return self._symbols

    @symbols.setter
    def symbols(self, symbols):
        """Sets the symbols of this Symbols.


        :param symbols: The symbols of this Symbols.
        :type symbols: str
        """

        self._symbols = symbols
